/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Table.userManagement;

import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author QCU
 */
public class UserCellPanelAction extends javax.swing.JPanel {

    /**
     * Creates new form UserCellPanelAction
     */
    public UserCellPanelAction() {
        initComponents();
        edit.setToolTipText("Edit");
        delete.setToolTipText("Mark as Done/Inactive");
    }
    
    public void initEvent(UserTableActionEvent event, int row){
        edit.addActionListener((ActionEvent e) -> {
            event.onEdit(row);
        });
        delete.addActionListener((ActionEvent e) -> {
            event.onStatus(row);
        });
    }
    
    public void setEditModeIcon(boolean isEditing){
        if (isEditing){
            edit.setIcon(new ImageIcon(getClass().getResource("/Table/check.png")));

        } else {
            edit.setIcon(new ImageIcon(getClass().getResource("/Table/edit.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit = new Table.ActionButton();
        delete = new Table.ActionButton();

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Table/edit.png"))); // NOI18N
        edit.setPreferredSize(new java.awt.Dimension(30, 30));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Table/ban.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Table.ActionButton delete;
    private Table.ActionButton edit;
    // End of variables declaration//GEN-END:variables
}
