/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import admin.AdminPage;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import jnafilechooser.api.JnaFileChooser;
import user.ClaimItem;
import user.PendingReportItem;
import user.Profile;
import user.Session;

public final class ItemDisplay extends javax.swing.JFrame {

    /**
     * Creates new form ItemDisplay
     */
    public ItemDisplay() {
        initComponents();
          displayAllItemsWithFilter(jScrollPane1, "lost");
        displayAllItemsWithFilter(jScrollPane3, "found");
        if (!jDialog1.isVisible()) {
            image[0] = null;
            fileName.setText("No file choosen");
        }
        r.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // 🔁 Refresh your table or panel here
                  displayAllItemsWithFilter(jScrollPane1, "lost");
    displayAllItemsWithFilter(jScrollPane3, "found");

            }
        });
    }
    final byte[][] image = new byte[1][];
    StringBuilder errors = new StringBuilder();
    user.ItemReport r = new user.ItemReport();
    int itemId;
    int userId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentNumField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inquiryArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        fileName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        fname1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tabPaneLostFound = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cardPanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cardPanel1 = new javax.swing.JPanel();

        jDialog1.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(390, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(390, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        jLabel2.setText("Other Information Provided In Your Profile");

        studentNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNumFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel3.setText("Student Number:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel4.setText("Inquiry:");

        inquiryArea.setColumns(20);
        inquiryArea.setRows(5);
        jScrollPane2.setViewportView(inquiryArea);

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel5.setText("Provide proof/ receipt:");

        fileLabel.setBackground(new java.awt.Color(255, 255, 255));
        fileLabel.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        fileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fileLabel.setText("Upload Photo");
        fileLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fileLabel.setMaximumSize(new java.awt.Dimension(150, 130));
        fileLabel.setMinimumSize(new java.awt.Dimension(150, 130));
        fileLabel.setPreferredSize(new java.awt.Dimension(150, 130));
        fileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileLabelMouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fileName.setText("No file choosen");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentNumField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fileName)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jDialog1.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        setSize(new java.awt.Dimension(1300, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel7.setBackground(new java.awt.Color(0, 39, 117));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qcu-logo.png"))); // NOI18N

        jLabel22.setBackground(new java.awt.Color(0, 51, 153));
        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Lost and Found");

        profile.setBackground(new java.awt.Color(255, 0, 0));
        profile.setFont(new java.awt.Font("Segoe UI Variable", 0, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user-4-32.png"))); // NOI18N
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });

        fname1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        fname1.setForeground(new java.awt.Color(255, 255, 255));
        fname1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(8, 8, 8))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 153));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(82, 700));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 51, 255));
        jPanel8.setMinimumSize(new java.awt.Dimension(32, 20));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 105, -1, 35));

        jPanel17.setBackground(new java.awt.Color(102, 102, 255));
        jPanel17.setOpaque(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 100, -1, -1));

        jPanel18.setBackground(new java.awt.Color(102, 102, 255));
        jPanel18.setOpaque(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 482, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("  Lost and Found");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 35));

        jLabel27.setBackground(new java.awt.Color(153, 153, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("  Pending Report");
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.setPreferredSize(new java.awt.Dimension(35, 20));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 30));

        jPanel9.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, -1));

        jLabel21.setBackground(new java.awt.Color(153, 153, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("  Claim Item");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setPreferredSize(new java.awt.Dimension(35, 20));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 35));

        jLabel19.setBackground(new java.awt.Color(153, 153, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("  Report Item");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setPreferredSize(new java.awt.Dimension(35, 20));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 30));

        jLabel20.setBackground(new java.awt.Color(153, 153, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("  Profile");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setPreferredSize(new java.awt.Dimension(35, 20));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 34));

        tabPaneLostFound.setBackground(new java.awt.Color(255, 255, 255));
        tabPaneLostFound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabPaneLostFound.setFocusable(false);
        tabPaneLostFound.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        tabPaneLostFound.setOpaque(true);
        tabPaneLostFound.setRequestFocusEnabled(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(50, 50));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        cardPanel.setBackground(new java.awt.Color(234, 234, 234));
        cardPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        cardPanel.setOpaque(false);
        cardPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(cardPanel);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        tabPaneLostFound.addTab("Lost Items ", jPanel12);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setFocusable(false);
        jScrollPane3.setMinimumSize(new java.awt.Dimension(50, 50));
        jScrollPane3.setOpaque(false);

        cardPanel1.setBackground(new java.awt.Color(234, 234, 234));
        cardPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        cardPanel1.setOpaque(false);
        cardPanel1.setPreferredSize(new java.awt.Dimension(1100, 600));

        javax.swing.GroupLayout cardPanel1Layout = new javax.swing.GroupLayout(cardPanel1);
        cardPanel1.setLayout(cardPanel1Layout);
        cardPanel1Layout.setHorizontalGroup(
            cardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        cardPanel1Layout.setVerticalGroup(
            cardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(cardPanel1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        tabPaneLostFound.addTab("Found Items", jPanel13);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaneLostFound)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tabPaneLostFound)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        getAccessibleContext().setAccessibleName("frame3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNumFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (studentNumField.getText().trim().isEmpty()) {
            errors.append("- Student Number is required\n");
        } else if (!studentNumField.getText().matches("^\\d{2}-\\d{4}$")) {
            errors.append("- Incorrect Student Number (format: 12-3456)\n");
        }

        if (inquiryArea.getText().trim().isEmpty()) {
            errors.append("- Inquiry is required\n");
        }

        if (errors.length() > 0) {
            JOptionPane.showMessageDialog(null, errors.toString(), "Validation Errors", JOptionPane.ERROR_MESSAGE);
        } else {

            try (Connection conn = DBConnection.DataBase.getConnection()) {
//                String getItemReport = "SELECT *, 'Reported' AS source FROM itemreport WHERE  UNION ALL SELECT *, 'Found' AS source FROM itemfound";
                String getUserQuery = "SELECT * FROM users_tbl WHERE schoolID = ?";
                PreparedStatement pstUser = conn.prepareStatement(getUserQuery);
                pstUser.setString(1, studentNumField.getText());
                ResultSet rst = pstUser.executeQuery();

                if (rst.next()) {
                    String firstName = rst.getString("firstName") + " " + rst.getString("lastName");
                    String yearSec = rst.getString("yearSec");
                    String studentNumber = rst.getString("schoolID");
                    String email = rst.getString("email");
                    String phone = rst.getString("phone");

                    if (studentNumber.equals(studentNumField.getText()) && tabPaneLostFound.getSelectedIndex() == 1) {

                        String insertQuery = "INSERT INTO claims_tbl (fullName, yearSec, studentNumber, email, phone, inquiry, proofImage, claimId, status_claim, userId, whoClaim) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                        PreparedStatement pstInsert = conn.prepareStatement(insertQuery);
                        pstInsert.setString(1, firstName);
                        pstInsert.setString(2, yearSec);
                        pstInsert.setString(3, studentNumber);
                        pstInsert.setString(4, email);
                        pstInsert.setString(5, phone);
                        pstInsert.setString(6, inquiryArea.getText());
                        if (image == null || image[0] == null) {
                            JOptionPane.showMessageDialog(null, "Proof image is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }

                        pstInsert.setBytes(7, image[0]);
                        pstInsert.setInt(8, itemId);
                        pstInsert.setString(9, "Claim Pending");
                        pstInsert.setInt(10, userId);
                        pstInsert.setInt(11, rst.getInt("id"));
                        pstInsert.executeUpdate();

                        String insertQuerys = "UPDATE itemfound SET status=? WHERE id=? AND status='Posted'";
                        PreparedStatement pstInserts = conn.prepareStatement(insertQuerys);
                        pstInserts.setString(1, "Claim Pending");
                        pstInserts.setInt(2, itemId);
                        pstInserts.executeUpdate();

                        System.out.println(itemId);

                        JOptionPane.showMessageDialog(null, "Claim submitted successfully.");
                        jDialog1.dispose();
                    } else if (studentNumber.equals(studentNumField.getText()) && tabPaneLostFound.getSelectedIndex() == 0) {
                        String checkQuery = "SELECT id FROM itemreport WHERE id = ?";
                        PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
                        checkStmt.setInt(1, itemId);
                        ResultSet rsCheck = checkStmt.executeQuery();

                        if (!rsCheck.next()) {
                            JOptionPane.showMessageDialog(null, "Invalid claimId: No matching report found.", "Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }

                        String insertQuery = "INSERT INTO claimsLost_tbl (fullName, yearSec, studentNumber, email, phone, inquiry, proofImage, claimId, status_claim, userId, whoClaim) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                        PreparedStatement pstInsert = conn.prepareStatement(insertQuery);
                        pstInsert.setString(1, firstName);
                        pstInsert.setString(2, yearSec);
                        pstInsert.setString(3, studentNumber);
                        pstInsert.setString(4, email);
                        pstInsert.setString(5, phone);
                        pstInsert.setString(6, inquiryArea.getText());
                        if (image == null || image[0] == null) {
                            JOptionPane.showMessageDialog(null, "Proof image is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                        pstInsert.setBytes(7, image[0]);
                        pstInsert.setInt(8, itemId);
                        pstInsert.setString(9, "Claim Pending");
                        pstInsert.setInt(10, userId);
                        pstInsert.setInt(11, rst.getInt("id"));
                        pstInsert.executeUpdate();

                        String insertQuerys = "UPDATE itemreport SET status=? WHERE id=? AND status='Posted'";
                        PreparedStatement pstInserts = conn.prepareStatement(insertQuerys);
                        pstInserts.setString(1, "Claim Pending");
                        pstInserts.setInt(2, itemId);
                        pstInserts.executeUpdate();

                        System.out.println(itemId);

                        JOptionPane.showMessageDialog(null, "Claim submitted successfully.");
                        jDialog1.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Student Number does not match.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "User information not found.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(ClaimItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void fileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileLabelMouseClicked
        JnaFileChooser ch = new JnaFileChooser();
        ch.setMode(JnaFileChooser.Mode.Files);
        ch.addFilter("Image Files", "jpg", "jpeg", "png", "gif", "bmp", "jfif", "webp");

        if (ch.showOpenDialog(null)) {
            File f = ch.getSelectedFile();
            if (f != null) {
                fileName.setText(f.getName());
                image[0] = new admin.AdminPage().imageIconToBytes(new ImageIcon(f.getAbsolutePath()));

                ImageIcon icon = new ImageIcon(
                        new ImageIcon(f.getAbsolutePath()).getImage().getScaledInstance(150, 130, Image.SCALE_SMOOTH)
                );
                fileLabel.setText("");
                fileLabel.setIcon(icon);
            }
        }
    }//GEN-LAST:event_fileLabelMouseClicked
    
      private void componentShown(){
        if (Session.userId != null && Session.userSchoolId != null) {
            try (Connection conn = DBConnection.DataBase.getConnection()) {
                String getUserQuery = "SELECT * FROM users_tbl WHERE id = ?";
                PreparedStatement pstUser = conn.prepareStatement(getUserQuery);
                pstUser.setInt(1, Session.userId);
                ResultSet rs = pstUser.executeQuery();

                if (rs.next()) {
                    byte[] imgBytes = rs.getBytes("profile");
                    if (imgBytes != null) {
                        Image img = ImageIO.read(new ByteArrayInputStream(imgBytes));
                       Image scaledImg = img.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                        Image circleImg = makeRoundedCorner(scaledImg, 60, 60);
                        profile.setIcon(new ImageIcon(circleImg));
                    } else {
                        URL iconPath = getClass().getClassLoader().getResource("icons/user4-32.png");
                        if (iconPath != null) {
                            profile.setIcon(new ImageIcon(iconPath));
                        } else {
                            System.err.println("Default icon not found.");
                        }
                    }

                    // Update this with the actual column names
                    fname1.setText(rs.getString("lastName") + ", " + rs.getString("firstName"));
                }

            } catch (SQLException | IOException ex) {
                Logger.getLogger(ClaimItem.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            URL iconPath = getClass().getClassLoader().getResource("icons/user4-32.png");
            if (iconPath != null) {
                profile.setIcon(new ImageIcon(iconPath));
            }
            fname1.setText("");
        }
    }
    
    private Image makeRoundedCorner(Image image, int width, int height) {
    BufferedImage rounded = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = rounded.createGraphics();

    // Enable anti-aliasing
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    // Create a circular clip
    g2.setClip(new Ellipse2D.Float(0, 0, width, height));

    // Draw the original image inside the circle
    g2.drawImage(image, 0, 0, width, height, null);

    g2.dispose();
    return rounded;
}
    
    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        Profile windows = new Profile();
        windows.setVisible(true);
        dispose();
      
    }//GEN-LAST:event_profileMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked

    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        new PendingReportItem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Profile windows = new Profile();
        windows.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        new ClaimItem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        new ItemReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        componentShown();
    }//GEN-LAST:event_formComponentShown

    public static void isLogin() {
        if (user.Session.currentUsername == null) {
            JOptionPane.showMessageDialog(null, "Please login first.");
            new userAuth.Login().setVisible(true);
        } else {
            new AdminPage().setVisible(true);
        }

    }

    public void displayItemCards() {
        

        String query = "SELECT *, 'lost' AS type FROM itemreport WHERE status = 'Posted' AND reportId != ?";
        displayAllItemsWithFilter(jScrollPane1, "lost");

        JPanel newCardPanel = new JPanel(new Table.wrapLayout(FlowLayout.LEFT, 15, 15)) {
            @Override
            public Dimension getPreferredSize() {
                if (getParent() instanceof JViewport) {
                    int width = ((JViewport) getParent()).getWidth();
                    setSize(width, 0);
                }
                return super.getPreferredSize();
            }
        };

        newCardPanel.setBackground(Color.white);
        jScrollPane1.setViewportView(newCardPanel);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        try (Connection con = DBConnection.DataBase.getConnection(); PreparedStatement ps = con.prepareStatement(query)) {
            if (Session.userId != null) {
                ps.setInt(1, Session.userId);
            } else {
                ps.setInt(1, -1);
            }

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                JPanel card = createCard(rs, this);
                newCardPanel.add(card);
            }

            jScrollPane1.getViewport().addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    newCardPanel.revalidate();
                    newCardPanel.repaint();
                }
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
        }
    }

    public void displayItemCardsFound() {
        String query = "SELECT *, 'found' AS type FROM itemfound WHERE status = 'Posted' AND reportId != ?";
        
        displayAllItemsWithFilter(jScrollPane3, "found");
        JPanel newCardPanel = new JPanel(new Table.wrapLayout(FlowLayout.LEFT, 15, 15)) {
            @Override
            public Dimension getPreferredSize() {
                if (getParent() instanceof JViewport) {
                    int width = ((JViewport) getParent()).getWidth();
                    setSize(width, 0);
                }
                return super.getPreferredSize();
            }
        };

        newCardPanel.setBackground(Color.white);
        jScrollPane3.setViewportView(newCardPanel);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);

        try (Connection con = DBConnection.DataBase.getConnection(); PreparedStatement ps = con.prepareStatement(query)) {
            if (Session.userId != null) {
                ps.setInt(1, Session.userId);
            } else {
                ps.setInt(1, -1);
            }

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                JPanel card = createCard(rs, this);
                newCardPanel.add(card);
            }

            jScrollPane3.getViewport().addComponentListener(new ComponentAdapter() {
                @Override
                public void componentResized(ComponentEvent e) {
                    newCardPanel.revalidate();
                    newCardPanel.repaint();
                }
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
        }
    }

    private JPanel createCard(ResultSet rs, ItemDisplay id) throws Exception {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS)); // Allows scroll pane to fill the card
        card.setBackground(Color.WHITE);
        card.setPreferredSize(new Dimension(270, 480));
        card.setMaximumSize(new Dimension(270, 480));

        Timestamp createdAt = rs.getTimestamp("timestamp");
        String timeAgo = getTimeAgo(createdAt);
        JPanel timePanel = new JPanel();
        timePanel.setLayout(new BorderLayout());
        timePanel.setBorder(BorderFactory.createEmptyBorder(0, 0, 2, 0));
        timePanel.setBackground(Color.white);
        JLabel time = new JLabel(timeAgo);
        time.setFont(new Font("Segoe UI Variable", Font.PLAIN, 12));
        time.setForeground(new Color(137, 137, 137));
        time.setHorizontalAlignment(JLabel.LEFT);
        timePanel.add(time);

        // Image
        JLabel imageLabel = new JLabel();
        imageLabel.setHorizontalAlignment(JLabel.CENTER);
        imageLabel.setVerticalAlignment(JLabel.CENTER);

        byte[] imgBytes = rs.getBytes("imageAttach");
        if (imgBytes != null) {
            Image img = ImageIO.read(new ByteArrayInputStream(imgBytes));
            Image scaledImg = getScaledImage(img, 280, 200);
            imageLabel.setIcon(new ImageIcon(scaledImg));

        } else {
            imageLabel.setText("No Image");
        }

        JPanel imagePanel = new JPanel(new BorderLayout());
        imagePanel.add(imageLabel, BorderLayout.NORTH);
        imagePanel.setBackground(Color.WHITE);

        int width = 235;
        int height = 20;

        JPanel infos = new JPanel();
        infos.setBackground(Color.WHITE);
        Font font = new Font("Segoe UI Variable", Font.PLAIN, 14);

        itemId = rs.getInt("id");

        JLabel nameLabel = new JLabel(rs.getString("itemName"));
        nameLabel.setMinimumSize(new Dimension(width, (height + 10)));
        nameLabel.setPreferredSize(new Dimension(width, (height + 10)));
        nameLabel.setMaximumSize(new Dimension(width, (height + 10)));
        nameLabel.setFont(new Font("Segoe UI Variable", Font.BOLD, 16));
        infos.add(nameLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 20)));
        JLabel locationLabel = new JLabel("Location: " + rs.getString("location"));
        locationLabel.setMinimumSize(new Dimension(width, height));
        locationLabel.setPreferredSize(new Dimension(width, height));
        locationLabel.setMaximumSize(new Dimension(width, height));
        locationLabel.setFont(font);
        infos.add(locationLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 2)));

        JLabel dateLabel = new JLabel("Date Lost: " + rs.getString("dateLost"));
        dateLabel.setMinimumSize(new Dimension(width, height));
        dateLabel.setPreferredSize(new Dimension(width, height));
        dateLabel.setMaximumSize(new Dimension(width, height));
        dateLabel.setFont(font);
        infos.add(dateLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 2)));

        Timestamp timeLost = rs.getTimestamp("timeLost"); // ✅ not getString()
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
        JLabel timeLabel = new JLabel("Time: " + sdf.format(timeLost));

        timeLabel.setMinimumSize(new Dimension(width, height));
        timeLabel.setPreferredSize(new Dimension(width, height));
        timeLabel.setMaximumSize(new Dimension(width, height));
        timeLabel.setFont(font);
        infos.add(timeLabel);
        infos.add(Box.createRigidArea(new Dimension(0, 2)));

        String description = rs.getString("description");
        JLabel descLbl = new JLabel("<html><body style='width: 185px;'>Description: " + description + "</body></html>");
        descLbl.setFont(font);
        infos.add(descLbl);

        JPanel btnPanel = new JPanel();
        btnPanel.setBackground(Color.WHITE);
        String jlbl = "found".equals(rs.getString("type")) ? "Claim" : "Found this item";
        JButton claimBtn = new JButton(jlbl);
        claimBtn.setBorder(new Table.RoundedBorder(10));
        claimBtn.setBackground(new Color(0, 0, 204)); // nice blue
        claimBtn.setForeground(Color.WHITE);

        // optional: size
        claimBtn.setPreferredSize(new Dimension(240, 40));
        btnPanel.add(claimBtn);
        int ids = rs.getInt("id");
        int uId = rs.getInt("reportId");
        String itemName = rs.getString("itemName");
        String jlbls = "found".equals(rs.getString("type")) ? "Claim Item" : "Found item";
        claimBtn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (checkUserLogin(id)) {
                    // block if not logged in
                    openDialog(jlbls, itemName, id, ids, uId);

                }
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                claimBtn.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Make it look clickable
            }
        });

        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(
                new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
        contentPanel.setBackground(Color.white);
        imagePanel.setMaximumSize(new Dimension(280, 200));
        imagePanel.setBackground(Color.red);
        contentPanel.add(imagePanel);
        infos.setPreferredSize(new Dimension(280, 180));
        infos.setMaximumSize(new Dimension(280, 190));
        contentPanel.add(infos);
        btnPanel.setMaximumSize(new Dimension(260, 50));
        contentPanel.add(btnPanel);

        contentPanel.setPreferredSize(new Dimension(270, 450));
        contentPanel.setMaximumSize(new Dimension(270, 460));
        contentPanel.setBorder(BorderFactory.createLineBorder(Color.gray, 1));

        card.add(timePanel);
        card.add(contentPanel);

        return card;

    }
    
//    private void loadLostCards(JPanel newCardPanel, String selectedCategory) {
//    newCardPanel.removeAll();
//    String query = "SELECT *, 'lost' AS type FROM itemreport WHERE status = 'Posted' AND reportId != ?";
//    if (!"All".equals(selectedCategory)) {
//        query += " AND category = ?";
//    }
//
//    try (Connection con = DBConnection.DataBase.getConnection(); PreparedStatement ps = con.prepareStatement(query)) {
//        ps.setInt(1, Session.userId != null ? Session.userId : -1);
//        if (!"All".equals(selectedCategory)) {
//            ps.setString(2, selectedCategory);
//        }
//
//        ResultSet rs = ps.executeQuery();
//        while (rs.next()) {
//            JPanel card = createCard(rs, this);
//            newCardPanel.add(card);
//        }
//
//        newCardPanel.revalidate();
//        newCardPanel.repaint();
//
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
//    }
//}


   public void displayAllItemsWithFilter(JScrollPane scrollPane, String itemType) {
    String[] categories = {
        "All",
        "Personal Items (Accessories)",
        "Electronics (Cellphone)",
        "Stationery & School Supplies",
        "Sports Equipment",
        "Miscellaneous (Umbrella)",
        "Others"
    };

    // Create top panel with category filter and search bar
    JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
    JComboBox<String> categoryFilter = new JComboBox<>(categories);
    categoryFilter.setFont(new Font("Segoe UI Variable", Font.PLAIN, 14));
    topPanel.add(new JLabel("Filter by Category: "));
    topPanel.add(categoryFilter);
    
    // Time filter dropdown
    String[] timeFilterOptions = {"Any", "Recently", "Last 24 hours", "Last 7 days"};
    JComboBox<String> timeFilter = new JComboBox<>(timeFilterOptions);
    topPanel.add(new JLabel("Filter by Time: "));
    topPanel.add(timeFilter);

    // Create search bar
    JTextField searchField = new JTextField(20);
    searchField.setFont(new Font("Segoe UI Variable", Font.PLAIN, 14));
    topPanel.add(new JLabel("Search: "));
    topPanel.add(searchField);
   
    topPanel.setBackground(Color.WHITE);

    // Create the card panel
    JPanel cardPanel = new JPanel(new Table.wrapLayout(FlowLayout.LEFT, 15, 15)) {
        @Override
        public Dimension getPreferredSize() {
            if (getParent() instanceof JViewport) {
                int width = ((JViewport) getParent()).getWidth();
                setSize(width, 0);
            }
            return super.getPreferredSize();
        }
    };

    cardPanel.setBackground(Color.WHITE);
    // Combine topPanel and cardPanel into one vertical panel
    JPanel contentPanel = new JPanel();
    contentPanel.setLayout(new BoxLayout(contentPanel, BoxLayout.Y_AXIS));
    contentPanel.setBackground(Color.WHITE);
    contentPanel.add(topPanel);
    contentPanel.add(cardPanel);

    scrollPane.setViewportView(contentPanel);
    scrollPane.getVerticalScrollBar().setUnitIncrement(16);

    // Function to load data with filtering
    Runnable loadData = () -> {
        cardPanel.removeAll();

        String selectedCategory = (String) categoryFilter.getSelectedItem();
        String searchQuery = searchField.getText().trim();
        String selectedTimeFilter = (String) timeFilter.getSelectedItem();

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append(String.format(
                "SELECT *, '%s' AS type FROM %s WHERE status = 'Posted' AND reportId != ?",
                itemType,
                itemType.equals("lost") ? "itemreport" : "itemfound"));

        // Category filter
        if (!selectedCategory.equals("All")) {
            queryBuilder.append(" AND category = ?");
        }

        // Search filter
        if (!searchQuery.isEmpty()) {
            queryBuilder.append(" AND (itemName LIKE ? OR description LIKE ? OR location LIKE ? OR name LIKE ? OR studentNum LIKE ? OR yearsec LIKE ?)");
        }

        // Time filter (recently, last 24 hours, last 7 days)
        if (!selectedTimeFilter.equals("Any")) {
            String timeCondition = "";
            switch (selectedTimeFilter) {
                case "Recently":
                    timeCondition = " AND timestamp >= NOW() - INTERVAL 1 DAY";
                    break;
                case "Last 24 hours":
                    timeCondition = " AND timestamp >= NOW() - INTERVAL 1 DAY";
                    break;
                case "Last 7 days":
                    timeCondition = " AND timestamp >= NOW() - INTERVAL 7 DAY";
                    break;
            }
            queryBuilder.append(timeCondition);
        }

        // Build the full query
        String query = queryBuilder.toString();

        try (Connection con = DBConnection.DataBase.getConnection(); PreparedStatement ps = con.prepareStatement(query)) {
            ps.setInt(1, Session.userId != null ? Session.userId : -1);

            int paramIndex = 2;
            if (!selectedCategory.equals("All")) {
                ps.setString(paramIndex++, selectedCategory);
            }

            // Set search query parameters
            if (!searchQuery.isEmpty()) {
                ps.setString(paramIndex++, "%" + searchQuery + "%"); // itemName
                ps.setString(paramIndex++, "%" + searchQuery + "%"); // description
                ps.setString(paramIndex++, "%" + searchQuery + "%"); // location
                ps.setString(paramIndex++, "%" + searchQuery + "%"); // name
                ps.setString(paramIndex++, "%" + searchQuery + "%"); // studentNum
                ps.setString(paramIndex++, "%" + searchQuery + "%"); // yearsec
            }

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                JPanel card = createCard(rs, this);
                cardPanel.add(card);
            }

            cardPanel.revalidate();
            cardPanel.repaint();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
        }
    };

    // Initial load
    loadData.run();

    // Reload on filter change
    categoryFilter.addActionListener(e -> loadData.run());
    searchField.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            loadData.run();
        }
    });
    timeFilter.addActionListener(e -> loadData.run());
}



    Image getScaledImage(Image srcImg, int width, int height) {
        BufferedImage resizedImg = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.drawImage(srcImg, 0, 0, width, height, null);
        g2.dispose();

        return resizedImg;
    }

    private void openDialog(String jlbls, String itemName, JFrame id, int ids, int uId) {
        jDialog1.setTitle(jlbls + ": " + itemName);
        jDialog1.setVisible(true);
        jDialog1.pack();
        jDialog1.setLocationRelativeTo(id);
        itemId = ids;
        userId = uId;
        System.out.println(ids + ", " + uId);
    }

    public boolean checkUserLogin(JFrame parentFrame) {
        if (Session.currentUsername == null) {
            int choice = JOptionPane.showConfirmDialog(
                    parentFrame,
                    "You are not logged in. Do you want to login first?",
                    "Login Required",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

            if (choice == JOptionPane.YES_OPTION) {
                parentFrame.dispose(); // Only close if they choose to log in
                new userAuth.Login().setVisible(true);
                return false; // Allow continuing if logged in
            } else if (choice == JOptionPane.NO_OPTION || choice == JOptionPane.CLOSED_OPTION) {

                return false; // Block further action
            }
        }
        return true;

    }

    public String getTimeAgo(Timestamp past) {
        if (past == null) {
            return "Unknown time";
        }

        long millisecondsAgo = System.currentTimeMillis() - past.getTime();
        if (millisecondsAgo < 0) {
            return "In the future";
        }

        long seconds = millisecondsAgo / 1000;
        long minutes = seconds / 60;
        long hours = minutes / 60;
        long days = hours / 24;

        if (seconds < 10) {
            return "Just now";
        } else if (seconds < 60) {
            return seconds + " second" + (seconds == 1 ? "" : "s") + " ago";
        } else if (minutes < 60) {
            return minutes + " minute" + (minutes == 1 ? "" : "s") + " ago";
        } else if (hours < 24) {
            return hours + " hour" + (hours == 1 ? "" : "s") + " ago";
        } else {
            return days + " day" + (days == 1 ? "" : "s") + " ago";
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ItemDisplay().setVisible(true);
        });
//        isLogin();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel cardPanel1;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel fileName;
    private javax.swing.JLabel fname1;
    private javax.swing.JTextArea inquiryArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel profile;
    private javax.swing.JTextField studentNumField;
    private javax.swing.JTabbedPane tabPaneLostFound;
    // End of variables declaration//GEN-END:variables
}
