/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author QCU
 */
public class UserClaimComponents extends javax.swing.JPanel {

    /**
     * Creates new form UserClaimComponents
     */
    public UserClaimComponents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accept2 = new javax.swing.JButton();
        g7 = new javax.swing.JLabel();
        g6 = new javax.swing.JTextField();
        g5 = new javax.swing.JTextField();
        g4 = new javax.swing.JTextField();
        g3 = new javax.swing.JTextField();
        g2 = new javax.swing.JTextField();
        g1 = new javax.swing.JTextField();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        accept1 = new javax.swing.JButton();
        reject1 = new javax.swing.JButton();
        t6 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1190, 68));
        jPanel1.setMinimumSize(new java.awt.Dimension(1190, 68));
        jPanel1.setPreferredSize(new java.awt.Dimension(1190, 68));

        accept2.setBackground(new java.awt.Color(0, 255, 0));
        accept2.setForeground(new java.awt.Color(51, 51, 51));
        accept2.setText("Confirm");
        accept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept2ActionPerformed(evt);
            }
        });

        g7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        g7.setForeground(new java.awt.Color(102, 102, 102));
        g7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        g7.setText(".");

        g6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g6.setText("(Optional)");
        g6.setBorder(null);
        g6.setPreferredSize(new java.awt.Dimension(61, 20));

        g5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g5.setBorder(null);
        g5.setPreferredSize(new java.awt.Dimension(61, 20));

        g4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g4.setBorder(null);
        g4.setPreferredSize(new java.awt.Dimension(61, 20));
        g4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g4ActionPerformed(evt);
            }
        });

        g3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g3.setBorder(null);
        g3.setPreferredSize(new java.awt.Dimension(61, 20));

        g2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g2.setBorder(null);
        g2.setPreferredSize(new java.awt.Dimension(61, 20));

        g1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g1.setBorder(null);
        g1.setPreferredSize(new java.awt.Dimension(61, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(accept2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(g7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accept2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(3090, 67));
        setMinimumSize(new java.awt.Dimension(1190, 67));
        setPreferredSize(new java.awt.Dimension(1190, 67));

        t1.setBackground(new java.awt.Color(255, 255, 255));
        t1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        t2.setBackground(new java.awt.Color(255, 255, 255));
        t2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        t3.setBackground(new java.awt.Color(255, 255, 255));
        t3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        t4.setBackground(new java.awt.Color(255, 255, 255));
        t4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        t5.setBackground(new java.awt.Color(255, 255, 255));
        t5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        accept1.setBackground(new java.awt.Color(0, 255, 0));
        accept1.setForeground(new java.awt.Color(51, 51, 51));
        accept1.setText("Claim Confirmed");
        accept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept1ActionPerformed(evt);
            }
        });

        reject1.setBackground(new java.awt.Color(255, 0, 0));
        reject1.setForeground(new java.awt.Color(243, 238, 238));
        reject1.setText("Cancel");
        reject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reject1ActionPerformed(evt);
            }
        });

        t6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        t6.setForeground(new java.awt.Color(102, 102, 102));
        t6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        t6.setText(".");

        t7.setBackground(new java.awt.Color(255, 255, 255));
        t7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accept1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reject1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(t6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accept1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reject1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept1ActionPerformed
        String decision = "Claimed";
        try (Connection con = DBConnection.DataBase.getConnection()) {
            String update = "UPDATE itemreport SET status = ? WHERE id = ?";
            PreparedStatement ps = con.prepareStatement(update);
            ps.setString(1, decision);
            ps.setInt(2, claimId);
            
            String updateClaim = "UPDATE claims_tbl SET status_claim = ? WHERE claimId = ?";
            PreparedStatement pst = con.prepareStatement(updateClaim);
            pst.setString(1, decision);
            pst.setInt(2, claimId);
            pst.executeUpdate();
            
            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Confirmed Claimed");
                accept1.setText("Claimed");
                accept1.setEnabled(false);
                accept1.setBorderPainted(false);
                accept1.setContentAreaFilled(false);
                reject1.setVisible(false);
                repaint();
                revalidate();
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_accept1ActionPerformed

    private void reject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reject1ActionPerformed
         String decision = "Cancel Claimed";
        try (Connection con = DBConnection.DataBase.getConnection()) {
            String update = "UPDATE itemreport SET status = ? WHERE id = ?";
            PreparedStatement ps = con.prepareStatement(update);
            
            ps.setString(1, decision);
            ps.setInt(2, claimId);
            
            int results = ps.executeUpdate();
            if (results > 0 ) {
                JOptionPane.showMessageDialog(this, "Confirmed");
                accept1.setText("Cancelled");
                accept1.setEnabled(false);
                accept1.setBorderPainted(false);
                accept1.setContentAreaFilled(false);
                reject1.setVisible(false);
                repaint();
                revalidate();
            }

        } catch (Exception ex) {
             ex.printStackTrace();
        }
    }//GEN-LAST:event_reject1ActionPerformed

    private void accept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept2ActionPerformed

        String decision = "Claim Approved";
        try (Connection con = DBConnection.DataBase.getConnection()) {
            String updateClaim = "UPDATE itemreport SET name=?, studentNum=?, yearSec=?, email=?, phone=? status=? WHERE id=?";
            PreparedStatement ps = con.prepareStatement(updateClaim);
            

            ps.setString(1, g1.getText());
            ps.setString(2, g2.getText());
            ps.setString(3, g3.getText());
            ps.setString(4, g4.getText());
            ps.setString(5, g5.getText());
            ps.setString(6, decision);
            ps.setInt(7, claimId1);
            
            int result = ps.executeUpdate();

            String updates = "UPDATE claims_tbl SET retrievalInfo=?, status_claim=?, timestamp=CURRENT_TIMESTAMP WHERE claimid = ?";
            PreparedStatement pst = con.prepareStatement(updates);
            if (g6.getText().equals("(Optional)")) {
                pst.setString(1, g6.getText());
            } else {
                pst.setString(1, null);
            }
            pst.setString(2, decision);
            pst.setInt(3, claimId1);
            int results = pst.executeUpdate();
            if (results > 0 && result > 0) {
                JOptionPane.showMessageDialog(this, "Confirmed");
            }

        } catch (Exception ex) {
             ex.printStackTrace();
        }
    }//GEN-LAST:event_accept2ActionPerformed

    private void g4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g4ActionPerformed

    private int claimId;
    private int claimId1;

    
//    //Main Panel
    
    public void setClaimInfo(String fullName, String studentNum,
        String yearSec, String email, String phone, String timestamp, String inq, String status, int claimId) {
        this.claimId = claimId;
        t1.setText(fullName);
        t2.setText(studentNum);
        t3.setText(yearSec);
        t4.setText(email);
        t5.setText(phone);
        t6.setText(timestamp);

        if (inq == null || inq.isEmpty()) {
            t7.setText("(Optional)");
        } else {
            t7.setText(inq);
        }
        if (status.equalsIgnoreCase("Claimed")){
            accept1.setText("Claimed");
            accept1.setEnabled(false);
            accept1.setBorderPainted(false);
            accept1.setContentAreaFilled(false);
            reject1.setVisible(false);
        
        } else if (status.equalsIgnoreCase("Cancel Claimed")) {
            accept1.setText("Cancelled");
                accept1.setEnabled(false);
                accept1.setBorderPainted(false);
                accept1.setContentAreaFilled(false);
                reject1.setVisible(false);
               
        }
         repaint();
                revalidate();
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept1;
    private javax.swing.JButton accept2;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField g4;
    private javax.swing.JTextField g5;
    private javax.swing.JTextField g6;
    private javax.swing.JLabel g7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reject1;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    // End of variables declaration//GEN-END:variables
}
