/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package user;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author QCU
 */
public class UserGetInfo extends javax.swing.JPanel {

    /**
     * Creates new form UserGetInfo
     */
    public UserGetInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g4 = new javax.swing.JTextField();
        g3 = new javax.swing.JTextField();
        g2 = new javax.swing.JTextField();
        g1 = new javax.swing.JTextField();
        accept2 = new javax.swing.JButton();
        g6 = new javax.swing.JTextField();
        g5 = new javax.swing.JTextField();
        g7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1190, 69));

        g4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g4.setBorder(null);
        g4.setPreferredSize(new java.awt.Dimension(61, 20));
        g4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g4ActionPerformed(evt);
            }
        });

        g3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g3.setBorder(null);
        g3.setPreferredSize(new java.awt.Dimension(61, 20));

        g2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g2.setBorder(null);
        g2.setPreferredSize(new java.awt.Dimension(61, 20));

        g1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g1.setBorder(null);
        g1.setPreferredSize(new java.awt.Dimension(61, 20));

        accept2.setBackground(new java.awt.Color(0, 255, 0));
        accept2.setForeground(new java.awt.Color(51, 51, 51));
        accept2.setText("Confirm");
        accept2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept2ActionPerformed(evt);
            }
        });

        g6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g6.setText("(Optional)");
        g6.setBorder(null);
        g6.setPreferredSize(new java.awt.Dimension(61, 20));

        g5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        g5.setBorder(null);
        g5.setPreferredSize(new java.awt.Dimension(61, 20));

        g7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        g7.setForeground(new java.awt.Color(102, 102, 102));
        g7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        g7.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(g1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g6, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(175, 175, 175)
                .addComponent(accept2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(g7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(g7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(g6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accept2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accept2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept2ActionPerformed

        String decision = "Claim Approved";
        try (Connection con = DBConnection.DataBase.getConnection()) {
            String updateClaim = "UPDATE itemreport SET name=?, studentNum=?, yearSec=?, email=?, phone=?, status=? WHERE id=?";
            PreparedStatement ps = con.prepareStatement(updateClaim);

            ps.setString(1, g1.getText());
            ps.setString(2, g2.getText());
            ps.setString(3, g3.getText());
            ps.setString(4, g4.getText());
            ps.setString(5, g5.getText());
            ps.setString(6, decision);
            ps.setInt(7, claimId1);

            int result = ps.executeUpdate();

            String updates = "UPDATE claims_tbl SET retrievalInfo=?, status_claim=?, timestamp=CURRENT_TIMESTAMP WHERE claimid = ?";
            PreparedStatement pst = con.prepareStatement(updates);
            if (g6.getText().equals("(Optional)")) {
                pst.setString(1, g6.getText());
            } else {
                pst.setString(1, null);
            }
            pst.setString(2, decision);
            pst.setInt(3, claimId1);
            int results = pst.executeUpdate();
            if (results > 0 && result > 0) {
                accept2.setText("Claim Approved");
                accept2.setEnabled(false);
                accept2.setBorderPainted(false);
                accept2.setContentAreaFilled(false);
                repaint();
                revalidate();
                JOptionPane.showMessageDialog(this, "Confirmed");
            }   

        } catch (Exception ex) {
             ex.printStackTrace();
        }
    }//GEN-LAST:event_accept2ActionPerformed

    private void g4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g4ActionPerformed
    
   
    private int claimId1;
    
    public void getClaimInfo(String fullName, String studentNum,
        String yearSec, String email, String phone, String timestamp, String inq, String status, int claimId1) {
        this.claimId1 = claimId1;
        g1.setText(fullName);
        g2.setText(studentNum);
        g3.setText(yearSec);
        g4.setText(email);
        g5.setText(phone);
        g7.setText(timestamp);

        if (inq == null || inq.isEmpty()) {
            g6.setText("(Optional)");
        } else {
            g6.setText(inq);
        }
        if (status.equalsIgnoreCase("Claim Approved")){
             accept2.setText("Request Confirmed");
            accept2.setEnabled(false);
            accept2.setBorderPainted(false);
            accept2.setContentAreaFilled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept2;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField g4;
    private javax.swing.JTextField g5;
    private javax.swing.JTextField g6;
    private javax.swing.JLabel g7;
    // End of variables declaration//GEN-END:variables
}
