/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userAuth;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import user.ItemDisplay;
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        emailTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fullnameTxt = new javax.swing.JTextField();
        signupBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentNumTxt = new javax.swing.JTextField();
        loginLink = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);
        jPanel1.add(emailTxt);
        emailTxt.setBounds(80, 120, 380, 35);

        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 100, 50, 16);

        jLabel4.setText("Student Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 170, 110, 16);

        fullnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(fullnameTxt);
        fullnameTxt.setBounds(80, 50, 380, 35);

        signupBtn.setText("SIGN UP");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupBtn);
        signupBtn.setBounds(360, 360, 100, 38);

        jLabel1.setText("Full Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 30, 100, 16);
        jPanel1.add(passwordTxt);
        passwordTxt.setBounds(80, 270, 380, 35);

        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 250, 100, 16);
        jPanel1.add(studentNumTxt);
        studentNumTxt.setBounds(80, 190, 380, 35);

        loginLink.setText("<html>Already have an account? <a href='#'>Login</a></html>");
        loginLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLinkMouseClicked(evt);
            }
        });
        jPanel1.add(loginLink);
        loginLink.setBounds(280, 330, 180, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameTxtActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        String sUrl, sUser, sPass;
        String query;
        sUrl = "jdbc:MySQL://localhost:3306/lostandfound_db";
        sUser = "root";
        sPass = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");  // Connecting to database
            Connection con = DriverManager.getConnection(sUrl, sUser, sPass);

            // Collect error messages and validations
            StringBuilder errors = new StringBuilder();

            if (fullnameTxt.getText().trim().isEmpty()) {
                errors.append("- Full Name is required\n");
            }
            if (emailTxt.getText().trim().isEmpty()) {
                errors.append("- Email Address is required\n");
            }
            if (passwordTxt.getText().trim().isEmpty()) {
                errors.append("- Password is required\n");
            } else if (passwordTxt.getText().length() < 8) {
                errors.append("- Password must contain at least 8 characters\n");
            }
            if (studentNumTxt.getText().trim().isEmpty()) {
                errors.append("- Student Number is required\n");
            } else if (studentNumTxt.getText().length() != 7) {
                errors.append("- Incorrect Student Number (2X-XXXX)\n");
            } else {
                String checkQuery = "SELECT * FROM users_tbl WHERE schoolID = ?"; //Check if schoolID already exists
                PreparedStatement checkStmt = con.prepareStatement(checkQuery);
                checkStmt.setString(1, studentNumTxt.getText());
                ResultSet rs1 = checkStmt.executeQuery();
                if (rs1.next()) {
                    errors.append("- Student Number already exists in the system\n");
                }
                rs1.close();
                checkStmt.close();
            }

            
            if (errors.length() > 0) {
                jOptionPane1.showMessageDialog(this, errors.toString(), "Validation Errors", jOptionPane1.ERROR_MESSAGE);
            } else {
                //If no error proceed to inserting into database
                query = "INSERT INTO users_tbl (fullName, email, schoolID, password) VALUES (?, ?, ?, ?)";
                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setString(1, fullnameTxt.getText());
                pstmt.setString(2, emailTxt.getText());
                pstmt.setString(3, studentNumTxt.getText());
                pstmt.setString(4, passwordTxt.getText());
                pstmt.executeUpdate();

                fullnameTxt.setText("");
                emailTxt.setText("");
                studentNumTxt.setText("");
                passwordTxt.setText("");
                jOptionPane1.showMessageDialog(this, "Sign Up successfull", "Success", jOptionPane1.INFORMATION_MESSAGE);
                
                this.dispose(); // Close current form
                new ItemDisplay().setVisible(true);
            }
        } catch (Exception e) {
            jOptionPane1.showMessageDialog(null, "Error: "+e.getMessage(), "Database error", jOptionPane1.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_signupBtnActionPerformed

    private void loginLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseClicked
        Login login = new Login();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_loginLinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fullnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginLink;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField studentNumTxt;
    // End of variables declaration//GEN-END:variables
}
